# -*- coding: utf-8 -*-
"""Copy of EDAexam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sw9g7fFKGbTzNI15-E6LRMiRSoEP2Lzx
"""

import pandas as pd

df = pd.read_csv("diabetes.csv")

df

df.shape

df.isnull().sum()

df.dtypes

meanGlu = df['Glucose'].mean()
medGlu = df['Glucose'].median()
stdGlu = df['Glucose'].std()
meanBMI = df['BMI'].mean()
medBMI = df['BMI'].median()
medBMI = df['BMI'].median()
stdBMI = df['BMI'].std()

print(meanGlu,medGlu,stdGlu,meanBMI,medBMI,stdBMI)

import matplotlib.pyplot as plt

plt.hist(df['Age'], bins=30, edgecolor='white')
plt.xlabel('Age')
plt.ylabel('patients')

plt.show()

import seaborn as sns

correlation = df.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(correlation, fmt=".3f")
plt.show()

import matplotlib.ticker as ticker

sns.boxplot(x='Outcome',y='Insulin',data=df)
plt.gca().yaxis.set_major_locator(ticker.MaxNLocator(nbins=15))

